import Document, { Html, Head, Main, NextScript } from 'next/document'
import Script from 'next/script'

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return {
      ...initialProps,
      styles: <>{initialProps.styles}</>
    }
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          {/* <link rel="stylesheet" type="text/css" href="https://headlessui.dev/_next/static/css/4c7bf06b46b3f9950141.css"></link> */}
          {/* <script defer src='https://cdn.jsdelivr.net/npm/hls.js@latest'></script> */}
          {/* <script defer src='https://unpkg.com/audioworklet-polyfill/dist/audioworklet-polyfill.js'></script> */}
          <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css"></link>
          <Script src='https://cdn.jsdelivr.net/npm/hls.js@latest' strategy='beforeInteractive'></Script>
          <Script src='https://cdn.jsdelivr.net/npm/toastify-js' strategy='beforeInteractive'></Script>
          <Script src="https://cdn.jsdelivr.net/npm/chart.js" strategy='beforeInteractive'></Script>
          <Script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0-rc" strategy='beforeInteractive'></Script>
        </Head>
        <body>
          <Main>
            {/* <div id="waveform"></div> */}
          </Main>
          <NextScript>
          </NextScript>
        </body>
      </Html>
    )
  }
}

export default MyDocument